### ISSUE TITLE
Bean Instantiation Exception in grails testing

### ISSUE THREAD

**Issue by sadasivaiahgoli** [grails-guides/grails-controller-testing#3]
I am using grails 3.2.9 testing . When I run the test cases it gives Bean Instantion Excpetion . How can we resolve this. Beans are not created when I run test cases

**Comment by niravassar** [comment]
Hello,

If you are just injecting a service into the controller, you can Mock or Stub it and then set it in the controller.

see this as an example:

http://guides.grails.org/grails-controller-testing/guide/index.html#unitTestIndex

If you are using beans you can use the block below which will replicate bean creation as in resources.groovy

`    static doWithSpring = {
        myService(MyService)
    }`

Further if you need help, you can create a fork and i can download the code and try to help you out. Thanks.
